language: csharp
dist: trusty
mono: none
dotnet: 2.0.0
script:
  - cd antlr3/CpsConsoleApplication
  - dotnet build -f netcoreapp1.1 DotnetValidation.sln
  - dotnet build -f netcoreapp2.0 DotnetValidation.sln
  - cd ../..
  - mkdir nuget-dev
  - wget -O nuget-dev/Antlr4.4.6.5-dev.nupkg https://ci.appveyor.com/api/buildjobs/4w4okv0tqynbm6pd/artifacts/build%2Fnuget%2FAntlr4.4.6.5-dev.nupkg
  - wget -O nuget-dev/Antlr4.CodeGenerator.4.6.5-dev.nupkg https://ci.appveyor.com/api/buildjobs/4w4okv0tqynbm6pd/artifacts/build%2Fnuget%2FAntlr4.CodeGenerator.4.6.5-dev.nupkg
  - wget -O nuget-dev/Antlr4.Runtime.4.6.5-dev.nupkg https://ci.appveyor.com/api/buildjobs/4w4okv0tqynbm6pd/artifacts/build%2Fnuget%2FAntlr4.Runtime.4.6.5-dev.nupkg
  - cd antlr4/CpsConsoleApplication
  - dotnet build -f netcoreapp1.1 DotnetValidation.sln
  - dotnet build -f netcoreapp2.0 DotnetValidation.sln
  - cd ../..
  - cd antlr4/CpsConsoleApplicationJavaCodegen
  - unset _JAVA_OPTIONS
  - dotnet build -f netcoreapp1.1 DotnetValidation.sln
  - dotnet build -f netcoreapp2.0 DotnetValidation.sln
  - cd ../..
